apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-site-config
  namespace: flink
data:
  hive-site.xml: |
    <configuration>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>s3a://warehouse/</value>
      </property>
      <property>
        <name>fs.s3.impl</name>
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
      </property>
      <property>
        <name>fs.s3n.impl</name>
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
      </property>
      <property>
        <name>aws.region</name>
        <value>us-east-1</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <name>fs.s3a.access.key</name>
        <value>minio</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>minio123</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/metastore_db</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>postgres</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>postgres</value>
      </property>
      <property>
          <name>hive.metastore.uris</name>
          <value>thrift://hive.trino.svc.cluster.local:9083</value>
          <description>IP address (or fully-qualified domain name) and port of the metastore host</description>
      </property>
      <property>
          <name>hive.metastore.schema.verification</name>
          <value>true</value>
      </property>
    </configuration>