---
apiVersion: v1
kind: Secret
metadata:
  name: minio-admin
  namespace: trino
data:
  username: bWluaW8= # minio
  password: bWluaW8xMjM= # minio123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: trino
data:
  db: bWV0YXN0b3JlX2Ri #metastore_db
  password: cG9zdGdyZXM= #postgres
  user: cG9zdGdyZXM= #postgres
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
  namespace: trino
spec:
  template:
    spec:
      containers:
      - name: hive-metastore
        image: alexcpn/hivemetastore:3.1.3.5 # afonsoamachado/hive-metastore-standalone:1.0.0-beta
        imagePullPolicy: Always
        command: ["/opt/apache-hive-metastore-3.1.3-bin/bin/schematool"]
        args: ["--verbose" ,"-initSchema" , "-dbType", "postgres" , "-userName", "$(POSTGRES_USER)",
          "-passWord", "$(POSTGRES_USER)" , "-url", "jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/$(POSTGRES_DB)"]
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: password
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Service
metadata:
  name: hive
  namespace: trino
spec:
  ports:
  - port: 9083
  selector:
    app: metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive
  namespace: trino
spec:
  selector:
    matchLabels:
      app: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: hive-metastore
        image: alexcpn/hivemetastore:3.1.3.5 # afonsoamachado/hive-metastore-standalone:1.0.0-beta
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-admin
              key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-admin
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: password
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: metastore-cfg-vol
          mountPath: /opt/apache-hive-metastore-3.1.3-bin/conf/hive-site.xml
          subPath: hive-site.xml
        resources:
          requests:
            memory: "1G"
        #    cpu: 4
      volumes:
        - name: metastore-cfg-vol
          configMap:
            name: metastore-cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metastore-cfg
  namespace: trino
data:
  hive-site.xml: |2-
    <configuration>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>false</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <name>fs.s3a.fast.upload</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.access.key</name>
        <value>admin</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>adminpassword123</value>
      </property>
      <property>
        <name>metastore.task.threads.always</name>
        <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
      </property>
      <property>
        <name>metastore.expression.proxy</name>
        <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/metastore_db?allowPublicKeyRetrieval=true&amp;useSSL=false&amp;serverTimezone=UTC</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>postgres</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>postgres</value>
      </property>
      <property>
        <name>metastore.warehouse.dir</name>
        <value>s3a://warehouse</value>
      </property>
      <property>
        <name>metastore.thrift.port</name>
        <value>9083</value>
      </property>
      <property>
        <name>metastore.log4j.file</name>
        <value>/opt/metastore-log4j2.properties</value>
      </property>
    </configuration>
---