---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: postgres
data:
  db: bWV0YXN0b3JlX2Ri #metastore_db
  password: cG9zdGdyZXM= #postgres
  user: cG9zdGdyZXM= #postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-32-postgres
spec:
  capacity:
    storage: 32Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-32-postgres
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: spa-k8s-01
      containers:
        - name: postgres
          image: docker.io/postgres:16.2
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: port-1
      protocol: TCP
      port: 5432
  selector:
    app: postgres
  type: LoadBalancer