# ClusterIP - static IP
apiVersion: v1
kind: Service
metadata:
  name: singlestoredb
  namespace: sdb
  labels:
    app: singlestoredb
spec:
  type: ClusterIP
  clusterIP: 10.98.167.27
  selector:
    app: singlestoredb
  ports:
    # singlestoredb db port:
    - name: '3306'
      port: 3306
      targetPort: 3306
    # singlestoredb Studio port:
    - name: '8080'
      port: 8080
      targetPort: 8080