---
# Source: starburst-hive/templates/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret-starbursthive-starburst-hive
  namespace: trino
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaGFyYm9yLnN0YXJidXJzdGRhdGEubmV0L3N0YXJidXJzdGRhdGEiOiB7ImF1dGgiOiAiY0c5MkxXMXBiR3hsYm01cGRXMDZSM3BIVURWMmFHTkhXRlZyVG5CWmJRPT0ifX19
---
#same secret that is in the postgres namespace
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: trino
data:
  db: bWV0YXN0b3JlX2Ri #metastore_db
  password: cG9zdGdyZXM= #postgres
  user: cG9zdGdyZXM= #postgres
---
# Source: starburst-hive/templates/expose/cluster-ip/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hive
  namespace: trino
  labels:
    app: starburst-hive
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9083
  selector:
    app: starburst-hive
---
# Source: starburst-hive/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive
  namespace: trino
  labels:
    app: starburst-hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starburst-hive
  template:
    metadata:
      labels:
        app: starburst-hive
      annotations:
        checksum/registry-secret: f1ad9f8e200f3c3afabc8c81fe5441904a409f5e7e5f778a8c14295ec38697b2
        checksum/init-file: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      imagePullSecrets:
        - name: registry-secret-starbursthive-starburst-hive
      containers:
        - name: hive
          image: harbor.starburstdata.net/starburstdata/hive:3.1.3-e.9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 9083
          env:
            # current docker container start script requires all this env variables even if not used
            - name: HIVE_METASTORE_JDBC_URL
              value: "jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/metastore_db"
            - name: HIVE_METASTORE_DRIVER
              value: "org.postgresql.Driver"
            - name: HIVE_METASTORE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: user
            - name: HIVE_METASTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
            - name: HIVE_METASTORE_WAREHOUSE_DIR
              value: "s3a://warehouse/"
            - name: HIVE_METASTORE_STORAGE_AUTHORIZATION
              value: "true"
            - name: REGION
              value: us-east-1
            - name: S3_ENDPOINT
              value: "http://minio.minio.svc.cluster.local:9000"
            - name: S3_ACCESS_KEY
              value: minio
            - name: S3_SECRET_KEY
              value: minio123
            - name: S3_PATH_STYLE_ACCESS
              value: "true"
            - name: GOOGLE_CLOUD_KEY_FILE_PATH
              value: 
            - name: AZURE_ABFS_OAUTH
              value:
            - name: AZURE_ABFS_OAUTH_TOKEN_PROVIDER
              value:
            - name: AZURE_ABFS_STORAGE_ACCOUNT
              value:
            - name: AZURE_ABFS_ACCESS_KEY
              value: 
            - name: AZURE_ABFS_OAUTH_CLIENT_ID
              value:
            - name: AZURE_ABFS_OAUTH_SECRET
              value: 
            - name: AZURE_ABFS_OAUTH_ENDPOINT
              value:
            - name: AZURE_WASB_STORAGE_ACCOUNT
              value:
            - name: AZURE_WASB_ACCESS_KEY
              value: 
            - name: AZURE_ADL_CLIENT_ID
              value:
            - name: AZURE_ADL_CREDENTIAL
              value: 
            - name: AZURE_ADL_REFRESH_URL
              value:
            - name: HIVE_METASTORE_HEAPSIZE_IN_KB
              value: "891289"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 9083
            periodSeconds: 10
            initialDelaySeconds: 120
          volumeMounts:
 
          terminationMessagePolicy: FallbackToLogsOnError
      volumes: