apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-catalogs
  namespace: trino
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-catalogs
  namespace: trino
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-catalogs
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem