---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-00
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-00
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-01
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-02
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-02
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-03
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-03
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-04
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-04
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-05
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-05
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-06
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /datadrives/datadrive00/pv-kafka-06
    server: 10.0.0.38 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  volumeMode: Filesystem

test.customerstreamjson